spider/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name='login'

urlpatterns = [
    url(r'^register',views.register,name='register'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^repwd',views.repwd,name='repwd'),
    url(r'',views.login,name='login'),
]

spider/spider/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homepage/', include('homepage.urls')),
    url(r'', include('login.urls')),
]

spider/apps/login/models.py
from django.db import models

# Create your models here.
#数据表的模型
class User(models.Model):
    username=models.CharField(max_length=64,unique=True)
    password=models.CharField(max_length=256)
    email=models.EmailField(unique=True)
    pnumber=models.CharField(max_length=11)
    sessionid=models.CharField(max_length=40,default='null')
    c_time=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.username
    class meta:
        ordering=['-c_time']
        verbose_name='用户'
        verbose_name_plural='用户'

spider/apps/login/forms.py
from django import forms

#创建表单类,用来产生表单
class UserForm(forms.Form):
    username=forms.CharField(label='用户名',max_length=64,widget=forms.TextInput(attrs={
        'placeholder':'用户名'}))
    password=forms.CharField(label='密码',max_length=16,widget=forms.PasswordInput(attrs={
        'placeholder':'密码'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=64, widget=forms.TextInput(attrs={
        'placeholder': '请设置用户名'}))
    password1 = forms.CharField(label='密码', max_length=16, widget=forms.PasswordInput(attrs={
        'placeholder': '请设置密码'}))
    password2 = forms.CharField(label='密码', max_length=16, widget=forms.PasswordInput(attrs={
        'placeholder': '请再次输入密码'}))
    email=forms.EmailField(label='邮箱地址',widget=forms.EmailInput(attrs={
        'placeholder': '请输入邮箱'}))
    pnumber=forms.CharField(label='性别',max_length=11,widget=forms.TextInput(attrs={
        'placeholder': '请输入手机号'}))

spider/apps/login/views.py
from django.shortcuts import render,redirect
from . import forms
from . import models
import hashlib

#这个负责加密密码,加一个salt防止撞库,
def hash_code(s, salt='mysite'):
    #采用SHA256加密算法
    h = hashlib.sha256()
    s += salt
    h.update(s.encode('utf-8'))  # update方法只接收bytes类型
    return h.hexdigest()
#用来产生会话
def create_session(request,user):
    request.session['is_login'] = True
    # 记录用户的id,username
    request.session['user_id'] = user.id
    request.session['user_name'] = user.username
    # 设置标志位用来标志这是新登录的账号,限制一个账号只能登录一个设备
    request.session['new'] = True
    if request.POST.get('savepwd'):
        request.session.set_expiry(60*60*24*7)
    else:
        request.session.set_expiry(0)


def login(request):
    #判断是否已经登录。登录了重定向到搜索页面
    if request.session.get('is_login',None):
        return redirect('/homepage/')
    if request.method=='POST':
        #发来的是post请求,根据发来数据生成表单类对象
        login_form=forms.UserForm(request.POST)
        message = '密码跟用户名不能为空'
        #判断数据的合法性
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                #查询数据库是否有相关的的用户
                user = models.User.objects.get(username=username)
                # 有用户的情况下判断密码是否正确,并且创建会话
                if user.password == hash_code(password):
                    create_session(request,user)
                    return redirect('/homepage/')
                else:
                    message = "用户不存在或密码不正确！"
            except:
                message = "用户不存在或密码不正确！"
            return render(request, 'login/login.html', locals())
    login_form = forms.UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    # 如果登录了就把他重定向到搜索页面
    if request.session.get('is_login',None):
        return redirect('/homepage')
    #如果是post请求则检查输入项
    if request.method=='POST':
        register_form=forms.RegisterForm(request.POST)
        message='请检查输入内容'
        #判断输入的合法性
        if register_form.is_valid():
            #如果合法表单类对象会把数据放到cleaned_data字典,取出对应的数据
            username=register_form.cleaned_data['username']
            password1=register_form.cleaned_data['password1']
            password2=register_form.cleaned_data['password2']
            email=register_form.cleaned_data['email']
            pnumber=register_form.cleaned_data['pnumber']
            #判断两次密码是否一致
            if password1!=password2:
                message='两次输入密码不同'
                return render(request,'login/register.html',locals())
            else:
                same_name_user=models.User.objects.filter(username=username)
                #检查用户名是否重复
                if same_name_user:
                    message='用户名已经存在。请重新选择用户名'
                    return render(request,'login/register.html',locals())
                same_name_user=models.User.objects.filter(email=email)
                #检查邮箱是否已经使用
                if same_name_user:
                    message='该邮箱已经被使用，请使用别的邮箱'
                    return render(request, 'login/register.html', locals())
                #数据没有问题则把数据存到数据库
                new_user=models.User()
                new_user.username=username
                #密码用SHA256加密算法加密储存
                new_user.password=hash_code(password1)
                new_user.email=email
                new_user.pnumber=pnumber
                new_user.save()
                #产生一个会话
                user = models.User.objects.get(username=username)
                create_session(request, user)
                # 把页面重定向到搜索界面
                return redirect('/homepage/')
    #如果不是post请求则生成一个空表单
    register_form=forms.RegisterForm()
    return render(request,'login/register.html',locals())

def repwd(request):
    # 如果登录了就把他重定向到搜索页面
    if request.session.get('is_login', None):
        return redirect('/homepage')
    # 如果是post请求则检查输入项
    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = '请检查输入内容'
        # 判断输入的合法性
        if register_form.is_valid():
            # 如果合法表单类对象会把数据放到cleaned_data字典,取出对应的数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            pnumber = register_form.cleaned_data['pnumber']
            # 判断两次密码是否一致
            if password1 != password2:
                message = '两次输入密码不同'
                return render(request, 'login/repwd.html', locals())
            else:
                # 检查用户名是否存在
                try:
                    user = models.User.objects.filter(username=username)[0]
                except:
                    message = '输入信息有误，请核对'
                    return render(request, 'login/repwd.html', locals())
                if user.email==email and user.pnumber==pnumber:
                    user.password=hash_code(password1)
                    user.save()
                    return redirect('/',locals())
                else:
                    #用户信息不存在则让用户检查
                    message='输入信息有误，请核对'
                    return render(request, 'login/repwd.html', locals())
    # 如果不是post请求则生成一个空表单
    register_form = forms.RegisterForm()
    return render(request, 'login/repwd.html', locals())


def logout(request):
    #用户退出登录则清除会话
    request.session.flush()
    return redirect('/')


spider/apps/login/templates/login/login.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<title>用户界面-登录</title>
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Career Multi Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Meta tag Keywords -->
<!-- css files -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS -->
<link rel="stylesheet" href="{% static  'css/font-awesome.css' %}"> <!-- Font-Awesome-Icons-CSS -->
<!-- //css files -->
<!--<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">-->

<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
</head>
<body>
<script src="{% static 'js/jquery.vide.min.js' %}"></script>
<!-- main -->
<div data-vide-bg="{% static 'video/Ipad' %}" style="width: 100%; height: 100%;">
<div class="center-container" style="width: 100%; height: 100%;">
<div class="w3ls-header">
		<h3>&nbsp;</h3>
	<div class="header-main">
		
	<div class="videologin">
		
		<div class="top-login first">
			<div class="border">
				<span><i class="fa fa-user-circle-o" aria-hidden="true"></i></span>
			</div>
		</div>
		<h2>登录</h2>
			<div class="header-bottom">
				<div class="header-right w3agile">
					<div class="header-left-bottom agileinfo">
						<form action="/login" method="post">
							{% csrf_token %}
							<div class="icon1">
								<i class="fa fa-user-o" aria-hidden="true"></i>
								{{ login_form.username }}
							</div>
							<div class="icon1">
								<i class="fa fa-unlock-alt" aria-hidden="true"></i>
								{{ login_form.password }}
							</div>
							<label class="anim">
								<input type="checkbox" class="checkbox" name="savepwd">
								<span> 七天免登陆 </span>
							</label>
							<a href="{% url 'login:repwd' %}" class="forgot">忘记密码</a>
              <a>{{ message }}</a>
							<div class="bottom">
								<input type="submit" id="dl" value="登录" />
								<input type="submit" id="zc" value="注册"onclick="javascript:location.href='/register'"/>
							</div>

						</form>	
					</div>
				</div>
			</div>
		</div>

		<div class="clear"></div>
	</div>
	
	<!-- copyright start here -->
	<div class="copyright">
		<p>Copyright © 2018 12亿资金项目团队 All Rights Reserved </p>
	</div>
	<!--copyright end here-->
</div>
<!--header end here-->
</div>
</div>
</body>
</html>

spider/apps/login/templates/login/register.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<title>用户界面-注册</title>
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Career Multi Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Meta tag Keywords -->
<!-- css files -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS -->
<link rel="stylesheet" href="{% static  'css/font-awesome.css' %}"> <!-- Font-Awesome-Icons-CSS -->
<!-- //css files -->
<!--<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">-->

<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
</head>
<body>
<script src="{% static 'js/jquery.vide.min.js' %}"></script>
<!-- main -->
<div data-vide-bg="{% static 'video/Ipad' %}" style="width: 100%; height: 100%;">
<div class="center-container" style="width:100%; height:100%;">
<div class="w3ls-header">
		<h3>&nbsp;</h3>
	<div class="header-main">

<div class="videoregister">
    <div class="top-login second">
      <div class="border">
        <span><i class="fa fa-user-circle" aria-hidden="true"></i></span>
      </div>
    </div>
    <h3>注册</h3>
      <div class="header-bottom">
        <div class="header-right w3agile">
          <div class="header-left-bottom agileinfo">
            <form action="/register" method="post">
              {% csrf_token %}
              <div class="icon1">
                <i class="fa fa-user-o" aria-hidden="true"></i>
                {{ register_form.username }}
              </div>
              <div class="icon1">
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                {{ register_form.email }}
              </div>
              <div class="icon1">
                <i class="fa fa-phone" aria-hidden="true"></i>  
                {{ register_form.pnumber }}
              </div>
              <div class="icon1">
                <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                {{ register_form.password1 }}
              </div>
              <div class="icon1">
                <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                {{ register_form.password2 }}
              </div>
              <a>{{ message }}</a>
              <div class="bottom">
                <input type="submit" id="dl" value="提交" />
                <input type="submit" id="zc" value="返回" onclick="javascript:location.href='/'"/>
              </div>
            </form> 
          </div>
        </div>
      </div>
    </div>

		<div class="clear"></div>
	</div>
	
	<!-- copyright start here -->
	<div class="copyright">
		<p>Copyright © 2018 12亿资金项目团队 All Rights Reserved </p>
	</div>
	<!--copyright end here-->
</div>
<!--header end here-->
</div>
</div>
</body>
</html>

spider/apps/login/templates/login/repwd.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<title>用户界面-重置密码</title>
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Career Multi Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Meta tag Keywords -->
<!-- css files -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS -->
<link rel="stylesheet" href="{% static  'css/font-awesome.css' %}"> <!-- Font-Awesome-Icons-CSS -->
<!-- //css files -->
<!--<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese" rel="stylesheet">-->

<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!-- //js -->
</head>
<body>
<script src="{% static 'js/jquery.vide.min.js' %}"></script>
<!-- main -->
<div data-vide-bg="{% static 'video/Ipad' %}" style="width: 100%; height: 100%;">
<div class="center-container" style="width:100%; height:100%;">
<div class="w3ls-header">
		<h3>&nbsp;</h3>
	<div class="header-main">

<div class="videoregister">
    <div class="top-login second">
      <div class="border">
        <span><i class="fa fa-user-circle" aria-hidden="true"></i></span>
      </div>
    </div>
    <h3>重置密码</h3>
      <div class="header-bottom">
        <div class="header-right w3agile">
          <div class="header-left-bottom agileinfo">
            <form action="/repwd" method="post">
              {% csrf_token %}
              <div class="icon1">
                <i class="fa fa-user-o" aria-hidden="true"></i>
                {{ register_form.username }}
              </div>
              <div class="icon1">
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                {{ register_form.email }}
              </div>
              <div class="icon1">
                <i class="fa fa-phone" aria-hidden="true"></i>  
                {{ register_form.pnumber }}
              </div>
              <div class="icon1">
                <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                {{ register_form.password1 }}
              </div>
              <div class="icon1">
                <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                {{ register_form.password2 }}
              </div>
              <a>{{ message }}</a>
              <div class="bottom">
                <input type="submit" id="dl" value="确认修改" />
                <input type="submit" id="zc" value="返回登录" onclick="javascript:location.href='/'"/>
              </div>
            </form> 
          </div>
        </div>
      </div>
    </div>

		<div class="clear"></div>
	</div>
	
	<!-- copyright start here -->
	<div class="copyright">
		<p>Copyright © 2018 12亿资金项目团队 All Rights Reserved </p>
	</div>
	<!--copyright end here-->
</div>
<!--header end here-->
</div>
</div>
</body>
</html>