spider/apps/homepage/urls.py
from django.conf.urls import url
from . import views

app_name='homepage'

urlpatterns = [
    url(r'^search',views.search,name='search'),
    url('',views.index,name='index'),
]

spider/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name='login'

urlpatterns = [
    url(r'^register',views.register,name='register'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^repwd',views.repwd,name='repwd'),
    url(r'',views.login,name='login'),
]

spider/spider/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homepage/', include('homepage.urls')),
    url(r'', include('login.urls')),
]

spider/apps/homepage/models.py
from django.db import models

# Create your models here.

spider/apps/homepage/views.py
from django.shortcuts import render,redirect
from . import check_user
from . import  douyin_info
from . import  douyin_video

def spider(request):
    url = request.GET.get('search')
    try:
        item = douyin_info.spider(url)
        start = douyin_video.Doyin_Download(url)
        video_url = start.get_download_url(start.get_url())
    except Exception as e:
        print(e)
    if 'item' in locals() and 'video_url' in locals():
        return render(request, 'homepage/search.html', {'item': item, 'video_url': video_url,'uname':request.session['user_name']})
    message='输入链接无效'
    return  render(request,'homepage/index.html',{'uname':request.session['user_name'],'message':message})


def index(request):
    #根据身份认证是否通过执行不同的响应
    if check_user.check_user(request):
        return render(request,'homepage/index.html',{'uname':request.session['user_name']})
    return redirect('/')

def search(request):
    # 根据身份认证是否通过执行不同的响应
    if check_user.check_user(request):
        return spider(request)
    return redirect('/')


spider/apps/homepage/templates/homepage/index.html
{% load staticfiles %}
<!-- <!doctype html> -->
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>抖音爬虫--12亿资金项目团队|中期项目</title>
	 <link rel="stylesheet" href="{% static 'css/index.css' %}">
     <script type="text/javascript">
        function searching(){
          document.getElementById("sub").value="正在搜索...";
          document.getElementById("sub").disabled=true;
          document.forms[0].submit();
        }
    </script>
 </head>
 <body>
  <div id="container" class="">
		<!-- 右侧导航栏 -->
		<div id="nav" class="">
			<ul id='rightNav'>
				<li><a href=#>首页</a>&nbsp;|&nbsp;</li>
				<li><a>{{ uname }}已登录</a>&nbsp;|&nbsp;</li>
				<li><a href="{% url 'login:logout' %}">退出</a></li>
			</ul>
		</div>
		<!-- 占位 -->
		<!-- <div class="zhanwei"></div> -->
		<!-- LOGO -->
		<div id="logo" class="">
			<a>
				<img src="{% static  'img/logo.png' %}" width="" height="" border="0" alt="">
			</a>
		</div>

          <a class="msg">{{ message }}</a>
	  <div class="s-bar">

	   	<form action="{% url 'homepage:search' %}" method="GET">
			  <input type="text" name="search" value="请输入抖音分享链接:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '请输入抖音分享链接:';}"><input type="submit"  value="搜索" onclick="searching()" id="sub">
	  	</form>
		</div>

		<!-- 使用教程 -->
		<div id="helper" class="">
			<p>使用教程：</p>
			<img src="{% static  'img/help1.png' %}" title='使用教程①'>
			<img src="{% static  'img/help2.png' %}" title='使用教程②'>
			<img src="{% static  'img/help3.png' %}" title='使用教程③'>
			<img src="{% static  'img/help4.png' %}" title='使用教程④'>
			<img src="{% static  'img/help5.png' %}" title='使用教程⑤'>
			<img src="{% static  'img/help6.png' %}" title='使用教程⑥'>
			<img src="{% static  'img/help7.png' %}" title='使用教程⑦'>
		</div>
			<!-- 底部 -->
		<div id="tfoot" class="">
			<p>Copyright&nbsp;&copy;&nbsp;2018&nbsp;12亿资金项目团队&nbsp;All&nbsp;Rights&nbsp;Reserved</p>
			<p>Complaint:&nbsp;hcanxuan@163.com</p>
			<p>达内教育|中期项目</p>
		</div>
  </div>


</body>
</html>

spider/apps/homepage/templates/homepage/search.html
{% load staticfiles %}
<!-- <!doctype html> -->
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>抖音爬虫--12亿资金项目团队|中期项目</title>
	<link rel='stylesheet' href="{% static 'css/search.css' %}">
<!-- 	<script type="text/javascript" src="js/jq.js"></script> -->
	<script type="text/javascript" src="{% static 'js/js.js' %}"></script>
 </head>
 <body>
  <div id="ttop" class="">
		<!-- 右侧导航栏 -->
		<div id="nav" class="">
			<img src="{% static 'img/logo.png' %}" width="" height="" border="0" alt="">
			<ul id='rightNav'>
				<li><a href="{% url 'homepage:index' %}">首页</a>&nbsp;|&nbsp;</li>
				<li><a>{{ uname }}已登录</a>&nbsp;|&nbsp;</li>
				<li><a href="{% url 'login:logout' %}">退出</a></li>
			</ul>
		</div>
		<p class='fenge'></p>
	<!-- 主体内容	 -->
	<div id="container" class="">
		<!-- 左侧个人资料 -->
		<div id="leftinfo" class="">
			<img id="userPhoto" src={{ item.head }} width="" height="" border="0" alt="">
			<div id="infoText" class="">			
				<p class='infoText'><img src="{% static 'img/id.png' %}">抖音ID：<span>{{item.douyin_id}}</span></p>
				<p class='infoText'><img src="{% static 'img/nc.png' %}">昵&nbsp;&nbsp;&nbsp;&nbsp;称：<span>{{ item.nick_name }}</span></p>
				<p class='infoText'><img src="{% static 'img/rz.png' %}">认&nbsp;&nbsp;&nbsp;&nbsp;证：<span> {{ item.info }}</span></p>
				<p class='infoText'><img src="{% static 'img/gz.png' %}">关&nbsp;&nbsp;&nbsp;&nbsp;注：<span>{{ item.guanzhu }} </span></p>
				<p class='infoText'><img src="{% static 'img/fs.png' %}">粉&nbsp;&nbsp;&nbsp;&nbsp;丝：<span>{{ item.fans }}</span></p>
				<p class='infoText'><img src="{% static 'img/dz.png' %}">点&nbsp;&nbsp;&nbsp;&nbsp;赞：<span>{{ item.zan }}</span></p>
				<p class='infoText'><img src="{% static 'img/zp.png' %}">作&nbsp;&nbsp;&nbsp;&nbsp;品：<span>{{ item.works }}</span></p>
				<p class='infoText'><img src="{% static 'img/xh.png' %}">喜&nbsp;&nbsp;&nbsp;&nbsp;欢：<span>{{ item.like_num }}</span></p>
			</div>
		</div>
	<!-- 右侧,视频列表 -->
		<div id="video_right" class="">
			<p class='left_title'>视频列表：</p>
			<div id="video_list" class="">
				{% for key,value in video_url.items %}
				<p class='videoList'>
					<input type="checkbox" name="check">
					<a target="_black" href="{{value}}" rel="noreferrer">{{ key }}</a>
				</p>
				{% endfor %}
			</div>
			<div id="listBtn" class="">
					<a href="javascript:void(0)" class='listBtn' id="allCheck">全选</a>
					<a href="javascript:void(0)" class='listBtn' id="ghostCheck">反选</a>
					<a href="javascript:void(0)" class='listBtn' id="noneCheck">取消</a>
					<a href="javascript:void(0)" class='listBtn' id="dowmCheck">复制链接</a>
					<div id="cptext" class="" style="width:1px;height:1px;border:none;color:white;overflow:hidden;"></div>
			</div>
		</div>
			<!-- 底部 --> 
		<div id="tfoot" class="">
			<p>Copyright&nbsp;&copy;&nbsp;2018&nbsp;12亿资金项目团队&nbsp;All&nbsp;Rights&nbsp;Reserved</p>
			<p>Complaint:&nbsp;123456@163.com</p>
			<p>达内教育|中期项目</p>
		</div>

	</div>

</body>
</html>